# https://wiki.hypr.land/Configuring/Keywords/
$terminal = foot
$wallpaperDisplay = awww-daemon
$statusBar = waybar
$fileManager = $terminal spf 
$appLauncher = rofi -show drun
$appSwitcher = rofi -show window
$webBrowser = firefox