[colors]
draw_bold_text_with_bright_colors = true

    [colors.primary]
    background = "0x1e2127"
    foreground = "0xabb2bf"
    bright_foreground = "0xe6efff"

    [colors.normal]
    black = "0x1e2127"
    red = "0xbe5046"
    green = "0x7a9f60"
    yellow = "0xd19a66"
    blue = "0x3b84c0"
    magenta = "0x9a52af"
    cyan = "0x3c909b"
    white = "0x828997"

    [colors.bright]
    black = "0x5c6370"
    red = "0xe06c75"
    green = "0x98c379"
    yellow = "0xe5c07b"
    blue = "0x61afef"
    magenta = "0xc678dd"
    cyan = "0x56b6c2"
    white = "0xe6efff"

    [colors.dim]
    black = "0x1e2127"
    red = "0xe06c75"
    green = "0x98c379"
    yellow = "0xd19a66"
    blue = "0x61afef"
    magenta = "0xc678dd"
    cyan = "0x56b6c2"
    white = "0x828791"